name: janitor

on:
  workflow_dispatch:
  workflow_call:
  issues:
    types: ["opened"]
  issue_comment:
  pull_request:
    types: ["opened"]
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'

jobs:

  triage:
    if: "${{ github.event_name == 'pull_requests' }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: label pull-request automatically. 
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

  greet:
    if: "${{ github.event_name == 'issues' || github.event_name == 'pull_requests' }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps: 
    - name: make sure new users feel welcome!
      if: "${{ github.event_name == 'issues' || github.event_name == 'pull_requests' }}"
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: |
          Hey! Thanks for the PR! We'll get right on that and get back to you.

          @fnctl
        issue-message: |
          Hey! Thanks for the Issue! We'll get right on that and get back to you.

          @fnctl

  stale:
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}"
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
    - name: close stale issues.
      uses: actions/stale@v5.0.0
      with:
        # Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # The message to post on the issue when tagging it. If none provided, will not mark iusses stale.
        # stale-issue-message: # optional
        # The message to post on the pr when tagging it. If none provided, will not mark prs stale.
        # stale-pr-message: # optional
        # The number of days old an issue can be before marking it stale
        # days-before-stale: # optional, default is 60
        # The number of days to wait to close an issue or pr after it being marked stale
        # days-before-close: # optional, default is 7
        # The label to apply when an issue is stale
        # stale-issue-label: # optional, default is Stale
        # The label to apply when a pr is stale
        # stale-pr-label: # optional, default is Stale
        # The maximum number of operations per run, used to control rate limiting
        # operations-per-run: # optional, default is 30
